# Project information
site_name: Openshift Builds
site_url: https://remkohdev.github.io/openshift-builds
site_author: IBM Developer

# Repository
repo_name: openshift-builds
repo_url: https://github.com/remkohdev/openshift-builds
edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome:
    - About the workshop: README.md
  - Workshop:
    - Setup: setup/README.md
    - Docker build: docker-build/README.md
    - Source-to-Image (S2I): https://ibm.github.io/s2i-open-liberty-workshop/
    - Pipeline build:
      - 1. Classic Pipeline with Jenkins: pipeline-build/lab-01/README.md
      - 2. OpenShift Pipeline with Jenkins: pipeline-build/lab-02/README.md
    - Tekton Deployment: https://ibm.github.io/tekton-tutorial-openshift/

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2021 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: ibm_8bar_reverse_2
  features:
    - navigation.tabs
    #- navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: black
    accent: blue
  custom_dir: overrides

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde